export const LOAD_USER_START   = "LOAD_USER_START";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL    = "LOAD_USER_FAIL";

export const CREATE_USER_START   = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL    = "CREATE_USER_FAIL";


export const DELETE_USER_START   = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL    = "DELETE_USER_FAIL";

export const UPDATE_USER_START   = "UPDATE_USER_START";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL    = "UPDATE_USER_FAIL";